config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
  devise_scope :user do
    delete 'sign_out', to: 'devise/session#destroy', as: :destroy_user_sessions
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :comments, only: [:index, :create]
  resources :friends, only: [:index, :show]
  resources :invitations, only: [:index, :destroy]
  get '/invitations/:id/invite', to: 'invitations#invite'
  get '/invitations/:id/accept', to: 'invitation#accept'
  resources :posts, only: [:create, :new, :index, :show]
  get '/posts/:id/like', to: 'posts#like'
  resources :users, only: [:index, :show]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :inviting_user, class_name: 'User'
    belongs_to :invited_user, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :author, class_name: 'User'
    has_many :likes

    def likes_number
        likes = Like.where(post_id: self.id)
        return likes.length
    end

    def comments_number
        comments = Comment.where(post_id: self.id)
        return likes.length
    end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic secure: true, size: 50, default: "identicon"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_and_belongs_to_many :friends,
    class_name: 'User',
    foreign_key: 'this_user_id',
    association_foreign_key: 'other_user_id'

  has_many :likes
  has_many :posts
  has_many :comments

  def posts
    @posts = Post.where(author_id: self.id)
  end

  def is_friend
    @friends = self.friends
    return true if @friends.includes(current_user)
    return false
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action: :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
        @post = Post.find(params[:id])
        @comments = Comment.where(post_id: @post.id)
    end

    def create
        @Comment.new(comment_params)
        if @Comment.save
            redirect_to posts_path
        else
            render :index, status: :unprocessable_entity
        end
    end

    private
    def comment_params
        params.require(:comment).permit!
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def index
        @friends = current_user.friends
    end

    def show
        @friend = current_user.friends.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @friends = Friend.first(10)
        @posts = Post.first(50)
        @comment = Comment.new
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    def index
        @invitations = Invitation.where(invited_user: current_user.id)
    end
    
    def invite
        @invitation = Invitation.new(accepted: false, inviting_user: current_user.id, invited_user: params[:id])
        if @invitation.save
            redirect_to root_path
        else
            render root_path, status: :unprocessable_entity
        end
    end

    def accept
        @user = current_user
        @invitation = Invitation.where(inviting_user_id: params[:id])
        @inviting_user = User.find(@invitation.inviting_user)
        @user.friends << @inviting_user
        @invitation.destroy
    end

    def destroy
        @invitation = Invitation.find(params[:id])
        @invitation.destroy
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def like
        @user = current_user
        @like = Like.where(user_id: current_user.id).where(post_id: params[:id])
        unless @like
            Like.create(user_id: current_user.id, post_id: params[:id])
            redirect_back(fallback_location: root_path)
        end
    end

    private
    def post_params
        params.require(:post).permit!
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = Users.all
        @invitations = Invitation.where(invited_user_id: current_user.id)
    end

    def show
        @user = Users.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/index.html.erb
<div class="frieds-list">
    <% @friends.each do |friend| %>
        <div class="friend">
            <%= link_to friend_path(friend) %>
                <div class="profile-img">
                    <%= image_tag friend.gravatar_url %>
                </div>
                <%= friend.username %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/friends/show.html.erb
<div class="container-friend">
    <div class="header">
        <div class="profile-img">
            <%= image_tag @friend.gravatar_url %>
        </div>
        <%= @friend.username %>
    </div>
    <div class="profile-frieds-list">
        <% @friend.friends.last(6).each do |friend| %>
            <div class="friend">
                <%= link_to friend_path(friend) %>
                    <div class="profile-img">
                        <%= image_tag friend.gravatar_url %>
                    </div>
                    <%= friend.username %>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="posts">
        <% @friend.posts.each do |post| %>
            <div class="post">
                <div class="author">
                    <div class="profile-img">
                        <%= image_tag author.gravatar_url %>
                    </div>
                    <%= linkt_to post.author, user_path(post.author) %>
                </div>
                <%= link_to post_path(post) %>
                    <h3 class="post-topic">
                        <%= post.title %>
                    </h3>
                    <p class="post-content">
                        <%= post.content %>
                    </p>
                <% end %>
                <div class="likes-comments">
                    <div class="likes">
                        <%= post.likes_number %>
                        <%= link_to 'Likes', "/post/#{post.id}/like" %>
                    </div>
                    <div class="comments-btn">
                        <%= post.comments_count %>
                        Comments
                    </div>
                </div>
                <div class="comments hidden">
                    <%= post.comments.last(10).each do |comment| %>
                        <div class="comment">
                            <h6 class="comment-author">
                                <div class="profile-img">
                                    <%= image_tag comment.user.gravatar_url %>
                                </div>
                                <%= comment.user %> 
                            </h6>
                            <%= comment.content %>
                        </div>
                    <% end %>
                    <%= form_with model: @comment do |f| %>
                        <%= f.text_field :content, placeholder: 'Write a comment...' %>
                        <%= f.submit 'Send' %>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div class="container">
    <div class="frieds-list">
        <% @friends.each do |friend| %>
            <div class="friend">
                <%= link_to friend_path(friend) %>
                    <div class="profile-img">
                        <%= image_tag friend.gravatar_url %>
                    </div>
                    <%= friend.username %>
                <% end %>
            </div>
        <% end %>
        <%= link_to 'See All Friends', friends_path %>
    </div>
    <div class="posts">
        <% @posts.each do |post| %>
            <div class="post">
                <div class="author">
                    <div class="profile-img">
                        <%= image_tag author.gravatar_url %>
                    </div>
                    <%= linkt_to post.author, user_path(post.author) %>
                </div>
                <%= link_to post_path(post) %>
                    <h3 class="post-topic">
                        <%= post.title %>
                    </h3>
                    <p class="post-content">
                        <%= post.content %>
                    </p>
                <% end %>
                <div class="likes-comments">
                    <div class="likes">
                        <%= post.likes_number %>
                        <%= link_to 'Likes', "/post/#{post.id}/like" %>
                    </div>
                    <div class="comments-btn">
                        <%= post.comments_count %>
                        Comments
                    </div>
                </div>
                <div class="comments hidden">
                    <%= post.comments.last(10).each do |comment| %>
                        <div class="comment">
                            <h6 class="comment-author">
                                <div class="profile-img">
                                    <%= image_tag comment.user.gravatar_url %>
                                </div>
                               <%= comment.user %> 
                            </h6>
                            <%= comment.content %>
                        </div>
                    <% end %>
                    <div class="comment-form">
                        <%= form_with model: @comment do |f| %>
                            <%= f.text_field :content, placeholder: 'Write a comment...' %>
                            <%= f.submit 'Send' %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="actions">
        <div class="action">
            <%= link_to 'Add Friends', users_path %>
        </div>
        <div class="action">
            <%= link_to 'See All Posts', posts_path %>
        </div>
        <div class="action">
            <%= link_to 'Post something', new_post_path %>
        </div>
    </div>
</div>