config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
  devise_scope :user do
    delete 'sign_out', to: 'devise/session#destroy', as: :destroy_user_sessions
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :comments, only: [:index, :create]
  resources :friends, only: [:index, :show]
  resources :invitations, only: [:index, :destroy]
  get '/invitations/:id/invite', to: 'invitations#invite'
  get '/invitations/:id/accept', to: 'invitation#accept'
  resources :posts, only: [:create, :new, :index, :show]
  get '/posts/:id/like', to: 'posts#like'
  resources :users, only: [:index, :show]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic secure: true, size: 50, default: "identicon"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_and_belongs_to_many :friends,
    class_name: 'User',
    foreign_key: 'this_user_id',
    association_foreign_key: 'other_user_id'

  has_many :likes
  has_many :posts
  has_many :comments

  def posts
    @posts = Post.where(author_id: self.id)
  end

  def is_friend
    @friends = self.friends
    return true if @friends.includes(current_user)
    return false
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :facebook

    def facebook
        @user = User.from_omniauth(request.env['omniauth.auth'])

        if @user.persisted?
            sign_in_and_redirect @user, event: :authentication
            set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
        else
            session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra)
            redirect_to new_user_registration_url
        end
    end

    def failure
        redirect_to root_path
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super do |resource|
      GreetingsMailer.with(user: resource).welcome_email.deliver_now
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = Users.all
        @invitations = Invitation.where(invited_user_id: current_user.id)
    end

    def show
        @user = Users.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
    <div class="invitations">
        <% @invitations.each do |invitation| %>
            <div class="invitation">
                <%= link_to user_path(invitation.inviting_user) %>
                    <div class="profile-img">
                        <%= image_tag invitation.inviting_user.gravatar_url %>
                    </div>
                    <%= invitation.inviting_user.username %>
                <% end %>
                wants to be your friend
                <div class="buttons">
                    <div class="accept-btn">
                        <%= link_to 'Accept', "invitations/#{invitation.inviting_user.id}/accept" %>
                    </div>
                    <div class="reject-btn">
                        <%= link_to 'Reject', destroy_invitation_path, method: :delete %>
                    </div>
                </div>
            <div>
        <% end %>
    </div>
    <div class="users-list">
        <% @users.each do |user| %>
            <div class="user">
                <%= link_to user_path(user) %>
                    <div class="profile-img">
                        <%= image_tag user.gravatar_url %>
                    </div>
                    <%= user.username %>
                <% end %>
                <% if user.is_friend %>
                    <div class="friendship-info">
                        You are already friends
                    </div>
                <% else %>
                    <div class="invite-btn">
                        <%= link_to 'Add Friend', "invitations/#{user.id}/invite" %>
                    </div>
                <%end%>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="header">
        <div class="profile-img">
            <%= image_tag @user.gravatar_url %>
        </div>
        <%= @user.username %>
    </div>
    <% if @user.is_friend %>
        <div class="friendship-info">
            You are already friends
        </div>
    <% else %>
        <div class="invite-btn">
        <%= link_to 'Add Friend', "invitations/#{user.id}/invite" %>
        </div>
    <%end%>
    <div class="profile-frieds-list">
        <% @user.friends.last(6).each do |friend| %>
            <div class="profile-friend">
                <%= link_to friend_path(friend) %>
                    <div class="profile-img">
                        <%= image_tag friend.gravatar_url %>
                    </div>
                    <%= friend.username %>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="posts">
        <% @user.posts.each do |post| %>
            <div class="post">
                <div class="author">
                    <div class="profile-img">
                        <%= image_tag author.gravatar_url %>
                    </div>
                    <%= linkt_to post.author, user_path(post.author) %>
                </div>
                <%= link_to post_path(post) %>
                    <h3 class="post-topic">
                        <%= post.title %>
                    </h3>
                    <p class="post-content">
                        <%= post.content %>
                    </p>
                <% end %>
                <div class="likes-comments">
                    <div class="likes">
                        <%= post.likes_number %>
                        <%= link_to 'Likes', "/post/#{post.id}/like" %>
                    </div>
                    <div class="comments-btn">
                        <%= post.comments_count %>
                        Comments
                    </div>
                </div>
                <div class="comments hidden">
                    <%= post.comments.last(10).each do |comment| %>
                        <div class="comment">
                            <h6 class="comment-author">
                                <div class="profile-img">
                                    <%= image_tag comment.user.gravatar_url %>
                                </div>
                                <%= comment.user %> 
                            </h6>
                            <%= comment.content %>
                        </div>
                    <% end %>
                    <%= form_with model: @comment do |f| %>
                        <%= f.text_field :content, placeholder: 'Write a comment...' %>
                        <%= f.submit 'Send' %>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>